import type { Metadata } from 'next'
import { M_PLUS_Rounded_1c } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import Nav from './components/Nav'
import { Locale, i18n } from '@/i18n.config'
import { getDictionary } from '@/lib/dictionary'

const mPlus = M_PLUS_Rounded_1c({
  weight: [ '400', '500', '700', '800', '900' ],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params: {lang}
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  const { nav } = await getDictionary(lang)

  return (
    <html lang={lang} className='dark'>
      <body className={`${mPlus.className} text-foreground bg-background`}>
        <Providers>
          <header>
            {/* todo: change to another nav provider */}
            <Nav lang={lang} dictionary={nav}/>
          </header>
          <main className='text-foreground bg-background'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
